project_info:
  name: "Living Dev Agent Project"
  version: "1.0.0"
  description: "Template for Living Dev Agent workflow with TLDL and DevTimeTravel integration"
  repository_url: "https://github.com/username/repo-name"
  
snapshot_config:
  # When to capture snapshots
  frequency: "on_commit"  # Options: daily, on_commit, manual, ci_only
  
  # What to include in snapshots
  include_patterns:
    - "src/**/*"
    - "docs/**/*"
    - "scripts/**/*"
    - "*.md"
    - "*.yaml"
    - "*.yml"
    - "*.json"
    - ".editorconfig"
    - ".gitignore"
    
  # What to exclude from snapshots  
  exclude_patterns:
    - "node_modules/**"
    - "*.tmp"
    - "*.log"
    - ".git/**"
    - "build/**"
    - "dist/**"
    - "__pycache__/**"
    - "*.pyc"
    - ".env*"
    - "*.lock"
    
context_capture:
  # Metadata to capture with each snapshot
  git_metadata: true          # Branch, commit hash, author, message
  file_checksums: true        # SHA256 hashes of included files
  dependency_graph: true      # Project dependencies and their versions
  build_artifacts: false     # Compiled outputs (usually too large)
  environment_vars: false    # Environment variables (security risk)
  
  # Development context
  active_branch: true         # Current git branch
  uncommitted_changes: true   # Working directory status
  recent_commits: 5          # Number of recent commits to include
  
snapshot_storage:
  # Where to store snapshots
  local_path: ".devtimetravel/snapshots"
  
  # Compression and retention
  compress: true              # Gzip compression for snapshots
  max_snapshots: 50          # Keep last N snapshots
  cleanup_after_days: 30     # Auto-delete snapshots older than N days
  
  # Optional remote storage
  remote_storage:
    enabled: false
    provider: "s3"            # s3, gcs, azure, github
    bucket: "your-bucket-name"
    prefix: "devtimetravel/"
    
integration:
  # CI/CD integration
  ci_enabled: true
  ci_on_pr: true              # Capture snapshot on PR creation/update
  ci_on_merge: true           # Capture snapshot on merge to main
  
  # Development tools integration
  pre_commit_hook: true       # Capture snapshot before commit
  post_commit_hook: false     # Capture snapshot after commit
  
  # IDE integration
  vscode_extension: true      # Enable VS Code extension
  jetbrains_plugin: true     # Enable JetBrains plugin
  
# Advanced settings
advanced:
  # Performance tuning
  max_file_size_mb: 10        # Skip files larger than this
  parallel_processing: true   # Use multiple threads for snapshot creation
  
  # Security
  sanitize_secrets: true      # Remove potential secrets from snapshots
  encryption_enabled: false  # Encrypt snapshots (requires key management)
  
  # DevTimeTravel-specific features
  timeline_view: true         # Enable timeline visualization
  diff_tracking: true         # Track file differences between snapshots
  code_evolution: true        # Track code evolution patterns
  
# Custom snapshot triggers
triggers:
  custom_commands:
    - name: "feature_complete"
      description: "Capture snapshot when feature is complete"
      command: "scripts/devtimetravel_snapshot.sh --tag feature_complete"
      
    - name: "before_refactor"
      description: "Capture snapshot before major refactoring"
      command: "scripts/devtimetravel_snapshot.sh --tag pre_refactor"
      
  file_patterns:
    # Trigger snapshot when these files change
    - pattern: "src/**/*.py"
      description: "Python source code changes"
      
    - pattern: "docs/TLDL*.md"
      description: "TLDL entry additions"